### ISSUE TITLE
Extract GLLimits and GLContextAttributes into a separate crate

### ISSUE THREAD

**Issue by jdm** [servo/surfman#128]
Right now whenever I modify rust-offscreen-rendering-context I have to rebuild the script crate in servo because it relies on these two structures. That makes me very sad.

**Comment by kvark** [comment]
Are you solely modifying the limits/attributes? Reading this comment might also lead to another way to approach this: refactor the `script` crate into multiple parts, make only a few of them depend on GL, none if possible ;)

**Comment by jdm** [comment]
Anything that starts with "refactor the script crate" turns out to be much harder in practice, unfortunately.

**Comment by kvark** [comment]
I was under impression that there was a successful GSoC project to split it...

**Comment by jdm** [comment]
I addressed this on the Servo side.
