### ISSUE TITLE
Support multiple textures

### ISSUE THREAD

**Issue by jdm** [servo/surfman#130]
For https://github.com/servo/servo/pull/21841 I would like to be able to have one texture that is ready for webrender at all times, and one texture that is ready for drawing. https://github.com/servo/rust-offscreen-rendering-context/compare/master...jdm:multiple is my attempt (along with https://github.com/servo/servo/compare/master...jdm:gl) but it's not working correctly yet. @emilio can you advise if I'm missing something?

**Comment by emilio** [comment]
so create_texture in that function does create a texture, but also binds it. So you'll leave the complete texture bound during setup, is that what you want?

**Comment by jdm** [comment]
Good point, thanks.

**Comment by jdm** [comment]
It actually unbinds before returning in create_texture.

**Comment by emilio** [comment]
pff, that's right, sorry, should've looked closer :(

I don't see anything obviously wrong with your code. I've noticed you changed the default clear color and such... I'd try to create some sort of reduced test-case that doesn't work as expected and run it with the MESA_DEBUG variable under linux, it generally points out all the dumb errors... Maybe you can cargo-cult something from [the existing unit tests](https://github.com/servo/rust-offscreen-rendering-context/blob/master/src/tests.rs)?

**Comment by jdm** [comment]
I think I sorted out the issues. Thanks for taking a look!
