### ISSUE TITLE
Remove metal dependency

### ISSUE THREAD

**Issue by kvark** [servo/surfman#209]
It's surprisingly used in the public API, and functionally only called with this:
> MetalDevice::all().into_iter().filter(|device| device.is_low_power())

Sine `metal` updates more often than `surfman`, it would be preferred to not depend on `metal`. In this case, just exposing `cocoa::id` in public API and issuing objc messages for that function should be enough.

**Comment by avr1** [comment]
@jdm Do you think this would be a good idea as well? If so, should I  change the return type to Strings?

**Comment by jdm** [comment]
I agree with kvark's assessment. We should replace MetalDevice in [this code](https://github.com/servo/surfman/blob/da1f89974581eefc808ea6190054a67120a5d6db/surfman/src/platform/macos/system/device.rs#L30) with a `cocoa::id` value instead, and we can copy [this code](https://github.com/gfx-rs/metal-rs/blob/4c1ad5b8a78fcb503364dbeac009ee056046f7a9/src/device.rs#L1442-L1462) and [this code](https://github.com/gfx-rs/metal-rs/blob/4c1ad5b8a78fcb503364dbeac009ee056046f7a9/src/device.rs#L1504-L1512) to replace the calls in [this code](https://github.com/servo/surfman/blob/da1f89974581eefc808ea6190054a67120a5d6db/surfman/src/platform/macos/system/device.rs#L44-L48).

**Comment by avr1** [comment]
Looking at the Metal code, it appears that they use both a Device and DeviceRef struct. htis solves the problem of the msg_send! not working with the device, but needing a reference. How much of the DeviceRef struct should I emulate, and should I make a NativeDevice consist of a Cocoa Id and a DeviceRef?

**Comment by jdm** [comment]
https://github.com/servo/surfman/blob/master/surfman/src/lib.rs

**Comment by jdm** [comment]
I remember taking a look back in December and deciding that the code we would need to duplicate didn't feel like a good tradeoff. I don't think this is worth pursuing.
