### ISSUE TITLE
offscreen example ConnectionFailed on Ubuntu Server or Docker container

### ISSUE THREAD

**Issue by colorhook** [servo/surfman#211]
I can't run the offscreen example on Ubuntu Server or docker, any example provide?

```
uname -a
```

output:

```
Linux GPU1 4.4.0-178-generic #208-Ubuntu SMP Sun Apr 5 23:45:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
locate libwayland-client.so
```

output:

```
/usr/lib/x86_64-linux-gnu/libwayland-client.so.0
/usr/lib/x86_64-linux-gnu/libwayland-client.so.0.3.0
```

**Comment by jdm** [comment]
What happens when you run it?

**Comment by colorhook** [comment]
```
RUST_BACKTRACE=1 cargo run --example offscreen a.png
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/$username/app/surfman/android-example/rust/Cargo.toml
workspace: /home/$username/app/surfman/Cargo.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/examples/offscreen a.png`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionFailed', surfman/examples/offscreen.rs:57:40
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: core::result::Result<T,E>::unwrap
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/result.rs:973
   4: offscreen::main
             at ./surfman/examples/offscreen.rs:57
   5: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by colorhook** [comment]
I use ubuntu server, not a desktop environment,  before `xvfb` using

```
glxinfo | grep rendering
```

output 

```
Error: unable to open display 
```

After using `xvfb`, the output become:

```
direct rendering: Yes
```

**Comment by jdm** [comment]
From the backtrace, that's https://github.com/servo/surfman/blob/afea998dc7ae48b0cc680542ab21176e21732a18/surfman/examples/offscreen.rs#L57. Presumably the failure comes from https://github.com/servo/surfman/blob/afea998dc7ae48b0cc680542ab21176e21732a18/surfman/src/platform/unix/x11/connection.rs#L84 or https://github.com/servo/surfman/blob/afea998dc7ae48b0cc680542ab21176e21732a18/surfman/src/platform/unix/wayland/connection.rs#L120 or https://github.com/servo/surfman/blob/afea998dc7ae48b0cc680542ab21176e21732a18/surfman/src/platform/unix/generic/connection.rs#L51.

**Comment by colorhook** [comment]
@jdm Thanks, I found a solution, the issue #174 may be the same as mine.

If I want doing offscreen rendering on Linux Server, I need `x11` or `wayland` first, note in `README.md`:

```
Linux/other Unix, with OpenGL on Wayland.

Linux/other Unix, with OpenGL on X11 via GLX.
```

#### Linux/other Unix, with OpenGL on X11 via GLX

`xvfb` is a virtual X server, I need run it first, for example:

```
Xvfb :0 -screen 0 640x480x8 -ac +extension GLX +render -noreset &
```

In the second, append `sm-x11` feature using in `Cargo.toml`.

```
[features]
default = ["sm-winit", "sm-x11"]
```

create a example file named `x11.rs` in `examples` directory:

```rust
use surfman::platform::unix::x11::connection::Connection;

fn main() {
  match Connection::new() {
    Ok(_) => {
      println!("x11 ok"); 
    },
    Err(e) => {
      println!("x11 error: {:?}", e);
    }
  }
}
```

run the example:

```
cargo run --example x11
```

got the output:

```
x11 ok
```

#### Linux/other Unix, with OpenGL on Wayland

Just installing the wayland library is not enough, I use `weston` also, which introduced in https://wayland.freedesktop.org/

**Part of the Wayland project is also the Weston reference implementation of a Wayland compositor**

After installing `weston`, set `XDG_RUNTIME_DIR` env variable

```
export XDG_RUNTIME_DIR=/tmp
```

run `weston`

```
weston &
```

create a example file named `wayland.rs` in `examples` directory:

```rust
use surfman::platform::unix::wayland::connection::Connection;

fn main() {
  match Connection::new() {
    Ok(_) => {
      println!("wayland ok"); 
    },
    Err(e) => {
      println!("x11 error: {:?}", e);
    }
  }
}
```

run the example:

```
cargo run --example wayland
```

got the output:

```
wayland ok
```
