### ISSUE TITLE
[Question] Is it Possible to Target MacOS With OpenGL ES 2.0?

### ISSUE THREAD

**Issue by zicklag** [servo/surfman#229]
I'm writing a game that uses OpenGL 2.0 for rendering and I'm using surfman and winit to create the graphics context and the window.

I don't have a mac, but a colleage of mine who does tested the game on their mac and get's a solid red screen.

I've heard that OpenGL is deprecated on MacOS before, so I'm not sure if that is the issue or not. I guess I'm mostly trying to get an idea of what the current state of OpenGL support on Mac is.

- Does OpenGL work on macs even though it is depracated and this is just an issue with my game?
- Is it possible to fall back to CPU rendering using mesa on Mac? ( My game is 2D and not super intense so the slowness might not be prohibitive )
- Can we use Angle to support OpenGL ES 2.0 on Metal? According to the angle README, OpenGL ES 2.0 is the only one supported on Metal so far, but that's what I'm already using so that would work for my app. 
- Are there any other options I should be aware of for putting an OpenGL app on MacOS?

**Comment by jdm** [comment]
Sorry,  the current maintainers of this crate do not have the experience required to answer any of those questions.

**Comment by zicklag** [comment]
OK, thanks for resonding anyway. :slightly_smiling_face:  :+1:
