### ISSUE TITLE
not_implemented selection into a feature

### ISSUE THREAD

**Issue by sotaroikeda** [servo/surfman#77]
Gecko webrender does not use offscreen_gl_context. But it is used by webrender and requests to  link to a gl library. It is nice if could remove the link in gecko webrender use case.

**Comment by emilio** [comment]
Yeah, I think I can figure something out. Alternatively, maybe making WR build without this crate is also desirable? If so, I can probably look into it (I'm the one that integrated those pieces into WR, and I think I could factor most of them into a self-contained, feature-gated place).

**Comment by sotaroikeda** [comment]
Yes, It is also nice if we could build WR without this crate.

**Comment by emilio** [comment]
See https://github.com/servo/webrender/issues/773

**Comment by emilio** [comment]
This was fixed long ago.
